// FILE: remoteSetupPlan.ts
// Purpose: Pure planning helpers for `synara setup` — remote-access mode
//          selection, environment-file and service-unit rendering, Tailscale
//          status parsing, and pairing URL construction. No I/O lives here so
//          every transformation is unit-testable.
// Layer: Server remote-setup planner

import { randomBytes } from "node:crypto";
import * as os from "node:os";
import * as path from "node:path";

import { Duration } from "effect";

import { isLoopbackHost } from "../startupAccess";

export const SETUP_PAIRING_TTL = Duration.minutes(30);
export const SETUP_SERVICE_NAME = "synara";
export const SETUP_ENV_FILE_NAME = "synara.env";
export const SETUP_HEALTH_TIMEOUT_MS = 30_000;
export const SETUP_HEALTH_INTERVAL_MS = 1_000;

export type RemoteSetupMode = "tailscale" | "public-url" | "insecure-lan" | "loopback";
export type RemoteServiceMode = "systemd-user" | "nohup" | "manual";

/**
 * The resolved server configuration the wizard commits to. `host` stays
 * loopback whenever a trusted edge (tailscale serve or a TLS proxy) terminates
 * remote traffic, so Synara never binds a public interface itself.
 */
export interface RemoteSetupConfig {
  readonly mode: RemoteSetupMode;
  readonly baseDir: string;
  readonly port: number;
  readonly host: string;
  readonly publicUrl?: string | undefined;
  readonly authToken: string;
  readonly allowInsecureRemote: boolean;
}

/** Random token for SYNARA_AUTH_TOKEN. URL-safe so it survives env files and shells. */
export const generateRemoteAuthToken = (): string => randomBytes(32).toString("base64url");

const SHELL_SAFE_VALUE = /^[A-Za-z0-9._~:\-/@%+=,]+$/u;

/**
 * Renders one KEY=value line usable both as a systemd EnvironmentFile entry and
 * as a POSIX `source`-able assignment. Values with whitespace or shell
 * metacharacters are single-quoted; embedded quotes are escaped POSIX-style.
 */
export function renderEnvironmentAssignment(key: string, value: string): string {
  if (SHELL_SAFE_VALUE.test(value)) return `${key}=${value}`;
  return `${key}='${value.replace(/'/g, `'\\''`)}'`;
}

/** Maps the resolved setup config to the environment the server runs with. */
export function buildSetupEnvironment(
  config: RemoteSetupConfig,
): ReadonlyArray<readonly [string, string]> {
  const entries: Array<readonly [string, string]> = [
    ["SYNARA_HOME", config.baseDir],
    ["SYNARA_PORT", String(config.port)],
    ["SYNARA_HOST", config.host],
    ["SYNARA_NO_BROWSER", "1"],
  ];
  if (config.authToken) entries.push(["SYNARA_AUTH_TOKEN", config.authToken]);
  if (config.publicUrl) entries.push(["SYNARA_PUBLIC_URL", config.publicUrl]);
  if (config.allowInsecureRemote) entries.push(["SYNARA_ALLOW_INSECURE_REMOTE", "1"]);
  return entries;
}

export function renderEnvironmentFile(config: RemoteSetupConfig): string {
  const lines = buildSetupEnvironment(config).map(([key, value]) =>
    renderEnvironmentAssignment(key, value),
  );
  return `# Synara remote setup — generated by \`synara setup\`. Keep this file private; it contains SYNARA_AUTH_TOKEN.\n${lines.join("\n")}\n`;
}

export interface SystemdUserServiceOptions {
  readonly serviceName: string;
  readonly description?: string;
  readonly envFilePath: string;
  /** Absolute path to the Node.js binary (`process.execPath`). */
  readonly executablePath: string;
  /** Absolute path to the server entrypoint (`dist/index.mjs`). */
  readonly entrypointPath: string;
  readonly workingDirectory?: string | undefined;
}

export function renderSystemdUserService(options: SystemdUserServiceOptions): string {
  const lines = [
    "[Unit]",
    `Description=${options.description ?? "Synara server"}`,
    "Documentation=https://github.com/Emanuele-web04/synara",
    "After=network-online.target",
    "Wants=network-online.target",
    "",
    "[Service]",
    "Type=simple",
    // EnvironmentFile holds SYNARA_AUTH_TOKEN, keeping the secret out of the
    // unit's world-readable ExecStart/process list.
    `EnvironmentFile=${options.envFilePath}`,
    `ExecStart=${options.executablePath} ${options.entrypointPath}`,
    "Restart=on-failure",
    "RestartSec=5s",
  ];
  if (options.workingDirectory) {
    lines.push(`WorkingDirectory=${options.workingDirectory}`);
  }
  lines.push("", "[Install]", "WantedBy=default.target", "");
  return lines.join("\n");
}

export interface TailscaleStatusSummary {
  readonly dnsName: string | undefined;
  readonly ipv4: string | undefined;
  readonly backendState: string | undefined;
}

/**
 * Parses `tailscale status --json`. Returns null on malformed JSON or when the
 * shape lacks Self entirely (never logged in / `tailscale up` never run).
 */
export function parseTailscaleStatus(rawJson: string): TailscaleStatusSummary | null {
  let decoded: unknown;
  try {
    decoded = JSON.parse(rawJson);
  } catch {
    return null;
  }
  if (!decoded || typeof decoded !== "object" || Array.isArray(decoded)) return null;
  const record = decoded as Record<string, unknown>;
  const self = record.Self;
  const selfRecord = self && typeof self === "object" ? (self as Record<string, unknown>) : null;
  const rawDnsName =
    typeof selfRecord?.DNSName === "string" ? selfRecord.DNSName.replace(/\.$/, "") : undefined;
  const ips = Array.isArray(record.TailscaleIPs) ? record.TailscaleIPs : undefined;
  const ipv4 = ips?.find(
    (entry): entry is string => typeof entry === "string" && entry.includes("."),
  );
  return {
    dnsName: rawDnsName && rawDnsName.length > 0 ? rawDnsName : undefined,
    ipv4,
    backendState: typeof record.BackendState === "string" ? record.BackendState : undefined,
  };
}

/**
 * Extracts the root (`/`) proxy targets from `tailscale serve status` output.
 * A stale mapping survives process death and reboots, so setup must detect
 * whether port 443's `/` mount already points at our server (idempotent) or at
 * something else (conflict — refuse rather than stack a broken route).
 */
export function parseTailscaleServeStatus(rawOutput: string): {
  readonly serving: boolean;
  readonly rootProxies: ReadonlyArray<string>;
} {
  const trimmed = rawOutput.trim();
  const empty = { serving: false, rootProxies: [] as const };
  if (!trimmed) return empty;
  try {
    const decoded: unknown = JSON.parse(trimmed);
    if (!decoded || typeof decoded !== "object") return empty;
    const web = (decoded as Record<string, unknown>).Web;
    if (!web || typeof web !== "object" || Array.isArray(web)) return empty;
    if (Object.keys(web).length === 0) return empty;
    const rootProxies: string[] = [];
    for (const hostEntry of Object.values(web)) {
      if (!hostEntry || typeof hostEntry !== "object") continue;
      const handlers = (hostEntry as Record<string, unknown>).Handlers;
      if (!handlers || typeof handlers !== "object" || Array.isArray(handlers)) continue;
      const root = (handlers as Record<string, unknown>)["/"];
      const proxy =
        root && typeof root === "object" ? (root as Record<string, unknown>).Proxy : undefined;
      if (typeof proxy === "string") rootProxies.push(proxy);
    }
    return { serving: true, rootProxies };
  } catch {
    // Text status: a non-empty "Available within your tailnet" block means
    // serving is configured, but targets aren't machine-readable — callers
    // should treat them as unknown rather than as absent.
    return { serving: /https?:\/\//.test(trimmed), rootProxies: [] };
  }
}

/**
 * Closed-set classification of `tailscale` stderr. Raw CLI output can carry
 * auth keys (`tskey-…`) and node names, so callers surface these labels (plus
 * their own wording) instead of echoing stderr verbatim into summaries.
 */
export type TailscaleDiagnostic =
  | "no-existing-handler"
  | "not-logged-in"
  | "permission-denied"
  | "unknown-flag"
  | "unknown";

export function tailscaleDiagnostic(stderrOrOutput: string): TailscaleDiagnostic | undefined {
  const text = stderrOrOutput.trim();
  if (!text) return undefined;
  if (/handler does not exist|no existing handler|serve config has no/i.test(text)) {
    return "no-existing-handler";
  }
  if (/not logged in|logged out|needs login|needs to log in|tailscaled not running/i.test(text)) {
    return "not-logged-in";
  }
  if (
    /permission denied|access denied|must be (root|run as root)|operation not permitted|requires root/i.test(
      text,
    )
  ) {
    return "permission-denied";
  }
  if (/unknown (flag|option)|flag provided but not defined|no such flag|unrecognized/i.test(text)) {
    return "unknown-flag";
  }
  return "unknown";
}

export interface CommandResultSummary {
  readonly ok: boolean;
  readonly exitCode: number;
  readonly output: string;
}

/** True when a failed CLI invocation looks like a privilege problem worth retrying via sudo -n. */
export function isPermissionFailure(result: CommandResultSummary): boolean {
  if (result.ok) return false;
  return /permission denied|access denied|not authorized|operation not permitted|must be run as root|requires root|is not allowed|sudo/i.test(
    result.output,
  );
}

/** True when the failure means the flag is unsupported (retry without it). */
export function isUnknownFlagFailure(result: CommandResultSummary, flag: string): boolean {
  if (result.ok) return false;
  // go-flag reports unknown long options single-dashed (`-yes`).
  const bare = flag.replace(/^-+/, "").toLowerCase();
  const rendered = new RegExp(`(?<![\\w-])-+${bare}(?![\\w-])`, "i");
  return (
    rendered.test(result.output) &&
    /unknown (flag|option)|flag provided but not defined|no such flag|unrecognized/i.test(
      result.output,
    )
  );
}

/** Builds the browser pairing URL exactly like `issueStartupPairingUrl` does. */
export function buildPairingUrl(baseUrl: string, credential: string): string {
  const url = new URL(baseUrl);
  url.pathname = "/pair";
  url.searchParams.delete("token");
  url.hash = new URLSearchParams([["token", credential]]).toString();
  return url.toString();
}

/** Origin used for local /health probes regardless of the public-facing URL. */
export function localProbeOrigin(config: Pick<RemoteSetupConfig, "host" | "port">): string {
  const host = isLoopbackHost(config.host) || config.host === "0.0.0.0" ? "127.0.0.1" : config.host;
  return `http://${host.includes(":") ? `[${host}]` : host}:${config.port}`;
}

/** The public origin the browser should reach; falls back to the bind address. */
export function publicFacingOrigin(config: RemoteSetupConfig): string {
  if (config.publicUrl) return new URL(config.publicUrl).origin;
  return localProbeOrigin(config);
}

export function systemdUserUnitDirectory(homeDirectory: string, xdgConfigHome?: string): string {
  return path.join(xdgConfigHome || path.join(homeDirectory, ".config"), "systemd", "user");
}

export function environmentFilePath(baseDir: string): string {
  return path.join(baseDir, SETUP_ENV_FILE_NAME);
}

/**
 * Validates an HTTPS root origin for `--public-url`, mirroring
 * `remoteAccessPolicyError` so the wizard fails before writing anything.
 */
export function validatePublicOrigin(raw: string): {
  readonly ok: boolean;
  readonly origin?: string;
  readonly reason?: string;
} {
  let url: URL;
  try {
    url = new URL(raw);
  } catch {
    return { ok: false, reason: `"${raw}" is not a valid URL.` };
  }
  if (url.protocol !== "https:") {
    return {
      ok: false,
      reason: `${raw} — public URL must use https (TLS termination happens at the proxy).`,
    };
  }
  if (url.username || url.password) {
    return { ok: false, reason: `${raw} — public URL must not contain credentials.` };
  }
  if (url.pathname !== "/" || url.search || url.hash) {
    return {
      ok: false,
      reason: `${raw} — public URL must be a root origin without path, query, or fragment.`,
    };
  }
  return { ok: true, origin: url.origin };
}

/** First non-loopback IPv4 on the box, used to build insecure-LAN access URLs. */
export function detectPrimaryLanIpv4(
  interfaces: NodeJS.Dict<os.NetworkInterfaceInfo[]> = os.networkInterfaces(),
): string | undefined {
  for (const infos of Object.values(interfaces)) {
    for (const info of infos ?? []) {
      if (info.family === "IPv4" && !info.internal) return info.address;
    }
  }
  return undefined;
}

export function isWildcardHost(host: string): boolean {
  return host === "0.0.0.0" || host === "::" || host === "*";
}

/**
 * The manual fallback the wizard prints: source the env file, then exec the
 * server entrypoint. The auth token never lands in shell history this way.
 */
export function renderManualStartInstructions(input: {
  readonly envFilePath: string;
  readonly executablePath: string;
  readonly entrypointPath?: string | undefined;
}): ReadonlyArray<string> {
  if (!input.entrypointPath) {
    // Source checkout (the argv entry is a .ts file): the packaged
    // `node dist/index.mjs` line doesn't apply, so point at the dev runner.
    return [
      `set -a; . ${input.envFilePath}; set +a`,
      `bun run --cwd apps/server start  # from the repository root`,
    ];
  }
  return [
    `set -a; . ${input.envFilePath}; set +a`,
    `exec ${input.executablePath} ${input.entrypointPath} --no-browser`,
  ];
}
