// FILE: remoteSetupPlan.ts
// Purpose: Pure planning helpers for `synara setup` — remote-access mode
//          selection, environment-file and service-unit rendering, Tailscale
//          status parsing, and pairing URL construction. No I/O lives here so
//          every transformation is unit-testable.
// Layer: Server remote-setup planner

import { randomBytes } from "node:crypto";
import * as os from "node:os";
import * as path from "node:path";

import { Duration } from "effect";

import { isLoopbackHost, isWildcardHost } from "../startupAccess";

export const SETUP_PAIRING_TTL = Duration.minutes(30);
export const SETUP_SERVICE_NAME = "synara";
export const SETUP_ENV_FILE_NAME = "synara.env";
export const SETUP_HEALTH_TIMEOUT_MS = 30_000;
export const SETUP_HEALTH_INTERVAL_MS = 1_000;

export type RemoteSetupMode = "tailscale" | "public-url" | "insecure-lan" | "loopback";
export type RemoteServiceMode = "systemd-user" | "nohup" | "manual";

/**
 * The resolved server configuration the wizard commits to. `host` stays
 * loopback whenever a trusted edge (tailscale serve or a TLS proxy) terminates
 * remote traffic, so Synara never binds a public interface itself.
 */
export interface RemoteSetupConfig {
  readonly mode: RemoteSetupMode;
  readonly baseDir: string;
  readonly port: number;
  readonly host: string;
  /** Set at config time; the tailscale path may correct it to the live serve port. */
  publicUrl?: string | undefined;
  readonly authToken: string;
  readonly allowInsecureRemote: boolean;
}

/** Random token for SYNARA_AUTH_TOKEN. URL-safe so it survives env files and shells. */
export const generateRemoteAuthToken = (): string => randomBytes(32).toString("base64url");

const SHELL_SAFE_VALUE = /^[A-Za-z0-9._~:\-/@%+=,]+$/u;

/**
 * Renders one KEY=value line usable both as a systemd EnvironmentFile entry and
 * as a POSIX `source`-able assignment. Values with whitespace or shell
 * metacharacters are single-quoted; embedded quotes are escaped POSIX-style.
 */
export function renderEnvironmentAssignment(key: string, value: string): string {
  if (SHELL_SAFE_VALUE.test(value)) return `${key}=${value}`;
  return `${key}='${value.replace(/'/g, `'\\''`)}'`;
}

/**
 * Single-quote a path for embedding in a `sh -c` command or printed shell
 * instructions. Required even when the path looks safe — a home dir like
 * `/home/first last` otherwise breaks `source`/`nohup` lines.
 */
export function shellQuotePath(value: string): string {
  if (SHELL_SAFE_VALUE.test(value)) return value;
  return `'${value.replace(/'/g, `'\\''`)}'`;
}

/**
 * Double-quote a path for systemd unit directives (ExecStart,
 * EnvironmentFile). `%` becomes `%%` so systemd's specifier expansion can't
 * mangle a path containing e.g. `%h`.
 */
export function systemdQuotePath(value: string): string {
  return `"${value.replace(/%/g, "%%").replace(/["\\]/g, "\\$&")}"`;
}

/** Maps the resolved setup config to the environment the server runs with. */
export function buildSetupEnvironment(
  config: RemoteSetupConfig,
): ReadonlyArray<readonly [string, string]> {
  const entries: Array<readonly [string, string]> = [
    ["SYNARA_HOME", config.baseDir],
    ["SYNARA_PORT", String(config.port)],
    ["SYNARA_HOST", config.host],
    ["SYNARA_NO_BROWSER", "1"],
  ];
  if (config.authToken) entries.push(["SYNARA_AUTH_TOKEN", config.authToken]);
  if (config.publicUrl) entries.push(["SYNARA_PUBLIC_URL", config.publicUrl]);
  if (config.allowInsecureRemote) entries.push(["SYNARA_ALLOW_INSECURE_REMOTE", "1"]);
  return entries;
}

export function renderEnvironmentFile(config: RemoteSetupConfig): string {
  const lines = buildSetupEnvironment(config).map(([key, value]) =>
    renderEnvironmentAssignment(key, value),
  );
  return `# Synara remote setup — generated by \`synara setup\`. Keep this file private; it contains SYNARA_AUTH_TOKEN.\n${lines.join("\n")}\n`;
}

export interface SystemdUserServiceOptions {
  readonly serviceName: string;
  readonly description?: string;
  readonly envFilePath: string;
  /** Absolute path to the Node.js binary (`process.execPath`). */
  readonly executablePath: string;
  /** Absolute path to the server entrypoint (`dist/index.mjs`). */
  readonly entrypointPath: string;
  readonly workingDirectory?: string | undefined;
  /** Optional path to append stdout/stderr to, alongside the journal. */
  readonly logFilePath?: string | undefined;
}

export function renderSystemdUserService(options: SystemdUserServiceOptions): string {
  const lines = [
    "[Unit]",
    `Description=${options.description ?? "Synara server"}`,
    "Documentation=https://github.com/Emanuele-web04/synara",
    "After=network-online.target",
    "Wants=network-online.target",
    // Bound restart storms from a config that always crashes on boot.
    "StartLimitIntervalSec=300",
    "StartLimitBurst=5",
    "",
    "[Service]",
    "Type=simple",
    // EnvironmentFile holds SYNARA_AUTH_TOKEN, keeping the secret out of the
    // unit's world-readable ExecStart/process list.
    `EnvironmentFile=${systemdQuotePath(options.envFilePath)}`,
    `ExecStart=${systemdQuotePath(options.executablePath)} ${systemdQuotePath(options.entrypointPath)}`,
    // A provider/agent child OOMing must not take down the control plane.
    "OOMPolicy=continue",
    "Restart=always",
    "RestartSec=5s",
  ];
  if (options.workingDirectory) {
    lines.push(`WorkingDirectory=${systemdQuotePath(options.workingDirectory)}`);
  }
  if (options.logFilePath) {
    // Journald covers most hosts; append-file keeps logs reachable where the
    // user journal isn't (minimal systemd, containers).
    lines.push(`StandardOutput=append:${systemdQuotePath(options.logFilePath)}`);
    lines.push(`StandardError=append:${systemdQuotePath(options.logFilePath)}`);
  }
  lines.push("", "[Install]", "WantedBy=default.target", "");
  return lines.join("\n");
}

export interface TailscaleStatusSummary {
  readonly dnsName: string | undefined;
  readonly ipv4: string | undefined;
  readonly backendState: string | undefined;
  /** Self.Online — false means the node can't accept tailnet traffic right now. */
  readonly online: boolean;
  /** dnsName is present in CertDomains — required for `serve` to mint HTTPS certs. */
  readonly httpsCerts: boolean;
}

/**
 * Parses `tailscale status --json`. Returns null on malformed JSON or when the
 * shape lacks Self entirely (never logged in / `tailscale up` never run).
 */
export function parseTailscaleStatus(rawJson: string): TailscaleStatusSummary | null {
  let decoded: unknown;
  try {
    decoded = JSON.parse(rawJson);
  } catch {
    return null;
  }
  if (!decoded || typeof decoded !== "object" || Array.isArray(decoded)) return null;
  const record = decoded as Record<string, unknown>;
  const self = record.Self;
  const selfRecord = self && typeof self === "object" ? (self as Record<string, unknown>) : null;
  const rawDnsName =
    typeof selfRecord?.DNSName === "string" ? selfRecord.DNSName.replace(/\.$/, "") : undefined;
  const ips = Array.isArray(record.TailscaleIPs) ? record.TailscaleIPs : undefined;
  const ipv4 = ips?.find(
    (entry): entry is string => typeof entry === "string" && isTailscaleCgnatIpv4(entry),
  );
  const certDomains = Array.isArray(record.CertDomains) ? record.CertDomains : [];
  const dnsName = rawDnsName && rawDnsName.length > 0 ? rawDnsName : undefined;
  return {
    dnsName,
    ipv4,
    backendState: typeof record.BackendState === "string" ? record.BackendState : undefined,
    online: selfRecord?.Online !== false,
    httpsCerts:
      dnsName !== undefined &&
      certDomains.some(
        (domain) => typeof domain === "string" && domain.replace(/\.$/, "") === dnsName,
      ),
  };
}

/** Tailscale nodes always carry an address inside 100.64.0.0/10. */
export function isTailscaleCgnatIpv4(ip: string): boolean {
  const parts = ip.split(".");
  if (parts.length !== 4) return false;
  const first = Number(parts[0]);
  const second = Number(parts[1]);
  return first === 100 && second >= 64 && second <= 127;
}

/**
 * Extracts the root (`/`) proxy targets from `tailscale serve status` output.
 * A stale mapping survives process death and reboots, so setup must detect
 * whether port 443's `/` mount already points at our server (idempotent) or at
 * something else (conflict — refuse rather than stack a broken route).
 */
export function parseTailscaleServeStatus(rawOutput: string): {
  readonly serving: boolean;
  readonly rootProxies: ReadonlyArray<string>;
  /** Each `/` mount's listen port (from the Web host:port key) paired with its
   *  target — `"<non-proxy>"` for Path/Text handlers that `serve` would still
   *  replace. */
  readonly rootMounts: ReadonlyArray<{ readonly port: number; readonly proxy: string }>;
  /** Serving state is on but mount targets couldn't be decoded — callers must
   *  not assume `/` is free. */
  readonly targetsUnknown: boolean;
} {
  const trimmed = rawOutput.trim();
  const empty = {
    serving: false,
    rootProxies: [] as const,
    rootMounts: [] as const,
    targetsUnknown: false,
  };
  if (!trimmed) return empty;
  try {
    const decoded: unknown = JSON.parse(trimmed);
    if (!decoded || typeof decoded !== "object") return empty;
    const web = (decoded as Record<string, unknown>).Web;
    if (!web || typeof web !== "object" || Array.isArray(web)) return empty;
    if (Object.keys(web).length === 0) return empty;
    const rootProxies: string[] = [];
    const rootMounts: Array<{ readonly port: number; readonly proxy: string }> = [];
    for (const [hostPort, hostEntry] of Object.entries(web)) {
      if (!hostEntry || typeof hostEntry !== "object") continue;
      const handlers = (hostEntry as Record<string, unknown>).Handlers;
      if (!handlers || typeof handlers !== "object" || Array.isArray(handlers)) continue;
      const root = (handlers as Record<string, unknown>)["/"];
      if (!root || typeof root !== "object") continue;
      const proxy = (root as Record<string, unknown>).Proxy;
      const target = typeof proxy === "string" ? proxy : "<non-proxy>";
      if (typeof proxy === "string") rootProxies.push(proxy);
      const port = Number(hostPort.slice(hostPort.lastIndexOf(":") + 1));
      if (Number.isInteger(port) && port > 0 && port < 65536) {
        rootMounts.push({ port, proxy: target });
      }
    }
    return { serving: true, rootProxies, rootMounts, targetsUnknown: false };
  } catch {
    // Text status: a non-empty "Available within your tailnet" block means
    // serving is configured, but targets aren't machine-readable — callers
    // should treat them as unknown rather than as absent.
    const serving = /https?:\/\//.test(trimmed);
    return { serving, rootProxies: [], rootMounts: [], targetsUnknown: serving };
  }
}

/**
 * Closed-set classification of `tailscale` stderr. Raw CLI output can carry
 * auth keys (`tskey-…`) and node names, so callers surface these labels (plus
 * their own wording) instead of echoing stderr verbatim into summaries.
 */
export type TailscaleDiagnostic =
  | "no-existing-handler"
  | "not-logged-in"
  | "permission-denied"
  | "unknown-flag"
  | "unknown";

export function tailscaleDiagnostic(stderrOrOutput: string): TailscaleDiagnostic | undefined {
  const text = stderrOrOutput.trim();
  if (!text) return undefined;
  if (/handler does not exist|no existing handler|serve config has no/i.test(text)) {
    return "no-existing-handler";
  }
  if (/not logged in|logged out|needs login|needs to log in|tailscaled not running/i.test(text)) {
    return "not-logged-in";
  }
  if (
    /permission denied|access denied|must be (root|run as root)|operation not permitted|requires root/i.test(
      text,
    )
  ) {
    return "permission-denied";
  }
  if (/unknown (flag|option)|flag provided but not defined|no such flag|unrecognized/i.test(text)) {
    return "unknown-flag";
  }
  return "unknown";
}

export interface CommandResultSummary {
  readonly ok: boolean;
  readonly exitCode: number;
  readonly output: string;
}

/** Strips tailscale auth-key material (tskey-…) from CLI output before it is shown. */
export function redactTailscaleSecrets(output: string): string {
  return output.replace(/tskey-[A-Za-z0-9_-]+/g, "tskey-…");
}

/** True when a failed CLI invocation looks like a privilege problem worth retrying via sudo -n. */
export function isPermissionFailure(result: CommandResultSummary): boolean {
  if (result.ok) return false;
  return /permission denied|access denied|not authorized|operation not permitted|must be run as root|requires root|is not allowed|sudo/i.test(
    result.output,
  );
}

/** True when the failure means a flag is unsupported (retry without it). */
export function isUnknownFlagFailure(result: CommandResultSummary, flag?: string): boolean {
  if (result.ok) return false;
  const phrased =
    /unknown (flag|option)|flag provided but not defined|no such flag|unrecognized/i.test(
      result.output,
    );
  if (!phrased) return false;
  if (flag === undefined) return true;
  // go-flag reports unknown long options single-dashed (`-yes`).
  const bare = flag.replace(/^-+/, "").toLowerCase();
  const rendered = new RegExp(`(?<![\\w-])-+${bare}(?![\\w-])`, "i");
  return rendered.test(result.output);
}

/** Builds the browser pairing URL exactly like `issueStartupPairingUrl` does. */
export function buildPairingUrl(baseUrl: string, credential: string): string {
  const url = new URL(baseUrl);
  url.pathname = "/pair";
  url.searchParams.delete("token");
  url.hash = new URLSearchParams([["token", credential]]).toString();
  return url.toString();
}

/** Origin used for local /health probes regardless of the public-facing URL. */
export function localProbeOrigin(config: Pick<RemoteSetupConfig, "host" | "port">): string {
  const host =
    isLoopbackHost(config.host) || isWildcardHost(config.host) ? "127.0.0.1" : config.host;
  return `http://${host.includes(":") ? `[${host}]` : host}:${config.port}`;
}

/** The public origin the browser should reach; falls back to the bind address. */
export function publicFacingOrigin(config: RemoteSetupConfig): string {
  if (config.publicUrl) return new URL(config.publicUrl).origin;
  return localProbeOrigin(config);
}

export function systemdUserUnitDirectory(homeDirectory: string, xdgConfigHome?: string): string {
  // The XDG spec requires absolute values; a relative one is invalid and falls
  // back to the default rather than resolving against the caller's cwd.
  const configHome =
    xdgConfigHome && path.isAbsolute(xdgConfigHome)
      ? xdgConfigHome
      : path.join(homeDirectory, ".config");
  return path.join(configHome, "systemd", "user");
}

export function environmentFilePath(baseDir: string): string {
  return path.join(baseDir, SETUP_ENV_FILE_NAME);
}

/**
 * Reads one `KEY=value` from env-file contents, understanding the quoting
 * `renderEnvironmentAssignment` emits (bare values and POSIX single-quoted
 * values with the '\'' escape).
 */
export function parseEnvironmentValue(contents: string, key: string): string | undefined {
  const prefix = `${key}=`;
  for (const line of contents.split("\n")) {
    if (!line.startsWith(prefix)) continue;
    const raw = line.slice(prefix.length);
    if (raw.startsWith("'")) {
      // Undo '…'\''…' POSIX single-quote escaping.
      const inner = raw.slice(1, raw.endsWith("'") ? -1 : undefined);
      return inner.replace(/'\\''/g, "'");
    }
    return raw;
  }
  return undefined;
}

/**
 * Validates an HTTPS root origin for `--public-url`, mirroring
 * `remoteAccessPolicyError` so the wizard fails before writing anything.
 */
export function validatePublicOrigin(raw: string): {
  readonly ok: boolean;
  readonly origin?: string;
  readonly reason?: string;
} {
  let url: URL;
  try {
    url = new URL(raw);
  } catch {
    return { ok: false, reason: `"${raw}" is not a valid URL.` };
  }
  if (url.protocol !== "https:") {
    return {
      ok: false,
      reason: `${raw} — public URL must use https (TLS termination happens at the proxy).`,
    };
  }
  if (url.username || url.password) {
    return { ok: false, reason: `${raw} — public URL must not contain credentials.` };
  }
  if (url.pathname !== "/" || url.search || url.hash) {
    return {
      ok: false,
      reason: `${raw} — public URL must be a root origin without path, query, or fragment.`,
    };
  }
  return { ok: true, origin: url.origin };
}

/** RFC1918 or carrier-grade-NAT space — the ranges LAN clients can actually reach. */
export function isPrivateLanIpv4(address: string): boolean {
  const parts = address.split(".").map(Number);
  if (parts.length !== 4 || parts.some((p) => !Number.isInteger(p) || p < 0 || p > 255)) {
    return false;
  }
  const [a, b] = parts;
  return (
    a === 10 ||
    (a === 172 && b !== undefined && b >= 16 && b <= 31) ||
    (a === 192 && b === 168) ||
    (a === 100 && b !== undefined && b >= 64 && b <= 127) ||
    (a === 169 && b === 254)
  );
}

/**
 * First non-loopback IPv4 on the box, used to build insecure-LAN access URLs.
 * Private-space addresses win over public ones — a VPN bridge or public NIC
 * listed first would produce a URL no LAN peer can open.
 */
export function detectPrimaryLanIpv4(
  interfaces: NodeJS.Dict<os.NetworkInterfaceInfo[]> = os.networkInterfaces(),
): string | undefined {
  const candidates: string[] = [];
  for (const infos of Object.values(interfaces)) {
    for (const info of infos ?? []) {
      if (info.family === "IPv4" && !info.internal) candidates.push(info.address);
    }
  }
  return candidates.find(isPrivateLanIpv4) ?? candidates[0];
}

export { isWildcardHost };
/**
 * The manual fallback the wizard prints: source the env file, then exec the
 * server entrypoint. The auth token never lands in shell history this way.
 */
export function renderManualStartInstructions(input: {
  readonly envFilePath: string;
  readonly executablePath: string;
  readonly entrypointPath?: string | undefined;
}): ReadonlyArray<string> {
  const envFile = shellQuotePath(input.envFilePath);
  if (!input.entrypointPath) {
    // Source checkout (the argv entry is a .ts file): the packaged
    // `node dist/index.mjs` line doesn't apply, so point at the dev runner.
    return [
      `set -a; . ${envFile}; set +a`,
      `bun run --cwd apps/server start  # from the repository root`,
    ];
  }
  return [
    `set -a; . ${envFile}; set +a`,
    `exec ${shellQuotePath(input.executablePath)} ${shellQuotePath(input.entrypointPath)} --no-browser`,
  ];
}
