/**
 * ControlPlaneKernel - Port interface over the minisqlite control-plane kernel.
 *
 * The kernel commits events, projection patches, and durable jobs in one
 * SQLite transaction and surfaces indeterminate outcomes explicitly
 * (`recoverTransaction` / `recoverClaim`). This service hides the native
 * `minisqlite-node` napi binding behind an Effect interface so tests can
 * substitute fakes and the `SYNARA_CONTROL_PLANE_KERNEL` flag can swap
 * implementations.
 *
 * @module ControlPlaneKernel
 */
import { Schema, ServiceMap } from "effect";
import type { Effect } from "effect";

export class ControlPlaneKernelError extends Schema.TaggedErrorClass<ControlPlaneKernelError>()(
  "ControlPlaneKernelError",
  {
    operation: Schema.String,
    /** Kernel error code, e.g. "Conflict" or "CommitIndeterminate". */
    code: Schema.String,
    detail: Schema.String,
    cause: Schema.optional(Schema.Defect),
  },
) {
  override get message(): string {
    return `Control-plane kernel error in ${this.operation} (${this.code}): ${this.detail}`;
  }
}

export interface KernelExpectedStreamVersion {
  readonly streamId: string;
  readonly version: number;
}

export interface KernelEventInput {
  /** 32-char hex; generated by the kernel when omitted. */
  readonly eventId?: string;
  readonly streamId: string;
  readonly eventType: string;
  readonly occurredAtMs: number;
  readonly payload?: Uint8Array;
}

export interface KernelProjectionPut {
  readonly key: Uint8Array;
  readonly value: Uint8Array;
}

export interface KernelProjectionPatch {
  readonly projection: string;
  readonly expectedVersion: number;
  readonly puts?: ReadonlyArray<KernelProjectionPut>;
  readonly deletes?: ReadonlyArray<Uint8Array>;
}

export interface KernelJobSpec {
  /** 32-char hex; generated by the kernel when omitted. */
  readonly jobId?: string;
  readonly queue: string;
  readonly partitionKey: string;
  readonly payload: Uint8Array;
  /** "reconcilable" (default) or "idempotent" (requires `idempotencyKey`). */
  readonly effectMode?: string;
  readonly idempotencyKey?: string;
  readonly notBeforeMs?: number;
  readonly maxAttempts?: number;
}

export interface KernelJobAck {
  readonly jobId: string;
  readonly leaseToken: string;
  readonly resultDigest?: Uint8Array;
}

export interface KernelJobResolution {
  readonly jobId: string;
  /** "retry", "markSucceeded", or "markDead". */
  readonly resolution: string;
}

export interface KernelCommitBatch {
  /**
   * 32-char hex; generated when omitted. Supply one to be able to recover
   * an indeterminate commit with `recoverTransaction`.
   */
  readonly transactionId?: string;
  readonly committedAtMs: number;
  readonly expectedStreamVersions?: ReadonlyArray<KernelExpectedStreamVersion>;
  readonly events?: ReadonlyArray<KernelEventInput>;
  readonly projectionPatches?: ReadonlyArray<KernelProjectionPatch>;
  readonly enqueueJobs?: ReadonlyArray<KernelJobSpec>;
  readonly ackJobs?: ReadonlyArray<KernelJobAck>;
  /** Explicit operator resolutions for jobs in the Uncertain state. */
  readonly resolveUncertainJobs?: ReadonlyArray<KernelJobResolution>;
}

export interface KernelCommitReceipt {
  readonly transactionId: string;
  readonly transactionSequence: number;
  readonly committedAtMs: number;
}

export interface KernelClaimRequest {
  readonly queue: string;
  readonly workerId: string;
  readonly nowMs: number;
  readonly leaseMs: number;
  readonly limit: number;
  /** When set, only this partition's ready head job is eligible for claiming. */
  readonly partitionKey?: string;
}

export interface KernelClaimedJob {
  readonly jobId: string;
  readonly queue: string;
  readonly partitionKey: string;
  readonly payload: Uint8Array;
  readonly workerId: string;
  readonly leaseToken: string;
  readonly attempt: number;
  readonly leaseExpiresAtMs: number;
  readonly idempotencyKey?: string;
}

/**
 * Outcome of `claimJobs` or `recoverClaim`. `kind` is "noop",
 * "maintenanceCommitted", "committed", or (recovery only) "absent".
 * `staleJobs` lists job IDs that committed under the claim but must not be
 * executed with the recovered tokens.
 */
export interface KernelClaimOutcome {
  readonly kind: string;
  readonly transactionId?: string;
  readonly jobs: ReadonlyArray<KernelClaimedJob>;
  readonly staleJobs: ReadonlyArray<string>;
}

export interface KernelLeaseExtensionReceipt {
  readonly jobId: string;
  readonly attempt: number;
  readonly leaseExpiresAtMs: number;
}

/**
 * Outcome of `recoverTransaction`: `kind` is "committed" (with the original
 * receipt) or "absent" (safe to resubmit the same batch).
 */
export interface KernelTransactionRecovery {
  readonly kind: string;
  readonly receipt?: KernelCommitReceipt;
}

export interface KernelJobInfo {
  readonly jobId: string;
  readonly queue: string;
  readonly partitionKey: string;
  readonly state: string;
  readonly attempt: number;
  readonly leaseExpiresAtMs?: number;
  readonly workerId?: string;
  readonly errorSummary?: string;
}

export interface KernelPersistedEvent {
  readonly transactionId: string;
  readonly globalSequence: number;
  readonly streamVersion: number;
  readonly eventId: string;
  readonly streamId: string;
  readonly eventType: string;
  readonly occurredAtMs: number;
  readonly payload: Uint8Array;
}

/**
 * ControlPlaneKernelShape - Service API over one open control-plane store.
 */
export interface ControlPlaneKernelShape {
  /** Effective `SYNARA_CONTROL_PLANE_KERNEL` mode this instance was built with. */
  readonly mode: "off" | "shadow" | "on";

  /** Atomically commit events, projection patches, and job operations. */
  readonly commit: (
    batch: KernelCommitBatch,
  ) => Effect.Effect<KernelCommitReceipt, ControlPlaneKernelError>;

  /** Claim ready jobs from one queue. */
  readonly claimJobs: (
    request: KernelClaimRequest,
  ) => Effect.Effect<KernelClaimOutcome, ControlPlaneKernelError>;

  /** Durably extend an active lease. */
  readonly extendLease: (input: {
    readonly jobId: string;
    readonly leaseToken: string;
    readonly newExpiryMs: number;
    readonly nowMs: number;
  }) => Effect.Effect<KernelLeaseExtensionReceipt, ControlPlaneKernelError>;

  /** Recover an indeterminate claim, reconstructing original lease tokens. */
  readonly recoverClaim: (input: {
    readonly transactionId: string;
    readonly nowMs: number;
  }) => Effect.Effect<KernelClaimOutcome, ControlPlaneKernelError>;

  /** Recover the outcome of an indeterminate commit. */
  readonly recoverTransaction: (
    transactionId: string,
  ) => Effect.Effect<KernelTransactionRecovery, ControlPlaneKernelError>;

  /** List jobs, optionally filtered by queue and state, in enqueue order. */
  readonly jobs: (input: {
    readonly queue?: string;
    readonly state?: string;
    readonly limit: number;
  }) => Effect.Effect<ReadonlyArray<KernelJobInfo>, ControlPlaneKernelError>;

  /** Get one projection entry by key. */
  readonly projectionGet: (input: {
    readonly projection: string;
    readonly key: Uint8Array;
  }) => Effect.Effect<Uint8Array | null, ControlPlaneKernelError>;

  /** The current version of a projection (0 when it does not exist). */
  readonly projectionVersion: (
    projection: string,
  ) => Effect.Effect<number, ControlPlaneKernelError>;

  /** The current durable version of a stream (0 when it does not exist). */
  readonly streamVersion: (streamId: string) => Effect.Effect<number, ControlPlaneKernelError>;

  /** Events with a global sequence strictly greater than `after`, oldest first. */
  readonly eventsAfter: (input: {
    readonly after: number;
    readonly limit: number;
  }) => Effect.Effect<ReadonlyArray<KernelPersistedEvent>, ControlPlaneKernelError>;

  /** Generate a new random 128-bit ID as a 32-char lower-case hex string. */
  readonly newId: () => Effect.Effect<string, ControlPlaneKernelError>;
}

/**
 * ControlPlaneKernel - Service tag for the control-plane kernel port.
 */
export class ControlPlaneKernel extends ServiceMap.Service<
  ControlPlaneKernel,
  ControlPlaneKernelShape
>()("synara/persistence/Services/ControlPlaneKernel") {}
